host: catch all exceptions from subprocess.run()
We don't want to report errors via exceptions, because there are various
cases where a similar error condition does not result in an exception.
Uniformly report errors via BinResult, even if that result is made up.

Before:

    $ python -c 'import ktoolbox.host as h; h.local.run("pwd", sudo=True, cwd="/root/")'
    2024-08-21 08:36:30.359 DEBUG   [th:139769835137920]: cmd[1;localhost]: call 'sudo /bin/sh -c pwd'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/src/ocp-traffic-flow-tests/ktoolbox/host.py", line 287, in run
        bin_result = self._run(
                     ^^^^^^^^^^
      File "/data/src/ocp-traffic-flow-tests/ktoolbox/host.py", line 476, in _run
        res = subprocess.run(
              ^^^^^^^^^^^^^^^
      File "/usr/lib64/python3.12/subprocess.py", line 548, in run
        with Popen(*popenargs, **kwargs) as process:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib64/python3.12/subprocess.py", line 1026, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib64/python3.12/subprocess.py", line 1955, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    PermissionError: [Errno 13] Permission denied: '/root/'

After:

    $ python -c 'import ktoolbox.host as h; h.local.run("pwd", sudo=True, cwd="/root/")'
    2024-08-21 08:36:35.510 DEBUG   [th:140648083168128]: cmd[1;localhost]: call 'sudo /bin/sh -c pwd'
    2024-08-21 08:36:35.510 DEBUG   [th:140648083168128]: cmd[1;localhost]: └──> 'sudo /bin/sh -c pwd': failed (exit 1); err="Host.run(): [Errno 13] Permission denied: '/root/'"