evaluator: improve error message when parsing "eval-config.yaml"
Previously we only got:

    ValueError: ".IPERF_TCP[0].Normal": mandatory key missing

Now we get:

    ValueError: Failure parsing 'eval-config.yaml': ".IPERF_TCP[0].Normal": mandatory key missing